#define _GNU_SOURCE
#include "ctfbot.h"
#include <openssl/evp.h>
#include <sys/random.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
static int execsql(sqlite3 *db,const char *s){char *e=NULL;int r=sqlite3_exec(db,s,0,0,&e);if(e)sqlite3_free(e);return r==SQLITE_OK?0:-1;}
void ctf_sha256(const char *s,char out[65]){unsigned char d[32];unsigned int l=0;EVP_MD_CTX *c=EVP_MD_CTX_new();EVP_DigestInit_ex(c,EVP_sha256(),NULL);EVP_DigestUpdate(c,s,strlen(s));EVP_DigestFinal_ex(c,d,&l);EVP_MD_CTX_free(c);for(unsigned i=0;i<32;i++)sprintf(out+i*2,"%02x",d[i]);out[64]=0;}
static unsigned rnd(void){unsigned x=0;if(getrandom(&x,sizeof x,0)!=(ssize_t)sizeof x){fprintf(stderr,"CSPRNG failure\n");exit(2);}return x;}
int ctf_open(ctf_ctx *c,const char *p){if(sqlite3_open(p,&c->db)!=SQLITE_OK)return -1;return execsql(c->db,"PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS players(user TEXT PRIMARY KEY,score INTEGER NOT NULL DEFAULT 0,solves INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS challenges(id INTEGER PRIMARY KEY AUTOINCREMENT,user TEXT NOT NULL,kind TEXT NOT NULL,prompt TEXT NOT NULL,answer_hash TEXT NOT NULL,points INTEGER NOT NULL,solved INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);");}
void ctf_close(ctf_ctx *c){if(c&&c->db)sqlite3_close(c->db);}
static int fill(sqlite3_stmt *s,ctf_challenge *o){memset(o,0,sizeof *o);o->id=sqlite3_column_int64(s,0);snprintf(o->user,sizeof o->user,"%s",sqlite3_column_text(s,1));snprintf(o->kind,sizeof o->kind,"%s",sqlite3_column_text(s,2));snprintf(o->prompt,sizeof o->prompt,"%s",sqlite3_column_text(s,3));snprintf(o->answer_hash,sizeof o->answer_hash,"%s",sqlite3_column_text(s,4));o->points=sqlite3_column_int(s,5);o->solved=sqlite3_column_int(s,6);return 0;}
int ctf_active(ctf_ctx *c,const char *u,ctf_challenge *o){sqlite3_stmt*s;sqlite3_prepare_v2(c->db,"SELECT id,user,kind,prompt,answer_hash,points,solved FROM challenges WHERE user=? AND active=1 ORDER BY id DESC LIMIT 1",-1,&s,0);sqlite3_bind_text(s,1,u,-1,SQLITE_TRANSIENT);int r=sqlite3_step(s);if(r==SQLITE_ROW)fill(s,o);sqlite3_finalize(s);return r==SQLITE_ROW?0:1;}
static void generate(const char*k,char *prompt,size_t pn,char *ans,size_t an,int *pts){static const char*words[]={"shadow","matrix","daemon","cipher","kernel","packet","binary","socket","vault","signal","hexagon","vector"};const char*w=words[rnd()%(sizeof words/sizeof words[0])];unsigned v=1000+rnd()%9000;char plain[96];snprintf(plain,sizeof plain,"%s%u",w,v);if(!strcmp(k,"sha256")){char h[65];ctf_sha256(plain,h);snprintf(prompt,pn,"Recover the generated word+4-digit suffix from this training SHA-256: %s",h);snprintf(ans,an,"%s",plain);*pts=150;}else if(!strcmp(k,"hex")){char tmp[192]={0};for(size_t i=0;i<strlen(plain);i++)sprintf(tmp+2*i,"%02x",(unsigned char)plain[i]);snprintf(prompt,pn,"Decode this hex string: %s",tmp);snprintf(ans,an,"%s",plain);*pts=75;}else{unsigned key=1+rnd()%25;char enc[96];for(size_t i=0;i<=strlen(plain);i++){char ch=plain[i];if(ch>='a'&&ch<='z')enc[i]=(char)('a'+(ch-'a'+key)%26);else enc[i]=ch;}snprintf(prompt,pn,"Caesar decode (rotation %u): %s",key,enc);snprintf(ans,an,"%s",plain);*pts=100;}}
int ctf_start(ctf_ctx*c,const char*u,const char*k,ctf_challenge*o){ctf_challenge a;if(ctf_active(c,u,&a)==0){*o=a;return 0;}char p[CTF_MAX_TEXT],ans[96],h[65];int pts;generate(k,p,sizeof p,ans,sizeof ans,&pts);ctf_sha256(ans,h);sqlite3_stmt*s;sqlite3_prepare_v2(c->db,"INSERT OR IGNORE INTO players(user) VALUES(?);",-1,&s,0);sqlite3_bind_text(s,1,u,-1,SQLITE_TRANSIENT);sqlite3_step(s);sqlite3_finalize(s);sqlite3_prepare_v2(c->db,"INSERT INTO challenges(user,kind,prompt,answer_hash,points) VALUES(?,?,?,?,?)",-1,&s,0);sqlite3_bind_text(s,1,u,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,k,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,p,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,h,-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,5,pts);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);return -1;}sqlite3_finalize(s);return ctf_active(c,u,o);}
int ctf_reset(ctf_ctx*c,const char*u,const char*k,ctf_challenge*o){sqlite3_stmt*s;sqlite3_prepare_v2(c->db,"UPDATE challenges SET active=0 WHERE user=? AND active=1",-1,&s,0);sqlite3_bind_text(s,1,u,-1,SQLITE_TRANSIENT);sqlite3_step(s);sqlite3_finalize(s);return ctf_start(c,u,k,o);}
int ctf_submit(ctf_ctx*c,const char*u,const char*a,int*award){ctf_challenge ch;if(ctf_active(c,u,&ch))return 2;char h[65];ctf_sha256(a,h);if(strcmp(h,ch.answer_hash))return 1;if(execsql(c->db,"BEGIN IMMEDIATE"))return -1;sqlite3_stmt*s;sqlite3_prepare_v2(c->db,"UPDATE challenges SET solved=1,active=0 WHERE id=? AND solved=0",-1,&s,0);sqlite3_bind_int64(s,1,ch.id);sqlite3_step(s);int changed=sqlite3_changes(c->db);sqlite3_finalize(s);if(changed){sqlite3_prepare_v2(c->db,"UPDATE players SET score=score+?,solves=solves+1 WHERE user=?",-1,&s,0);sqlite3_bind_int(s,1,ch.points);sqlite3_bind_text(s,2,u,-1,SQLITE_TRANSIENT);sqlite3_step(s);sqlite3_finalize(s);}execsql(c->db,"COMMIT");*award=changed?ch.points:0;return changed?0:3;}
int ctf_profile(ctf_ctx*c,const char*u,int*score,int*solves){sqlite3_stmt*s;sqlite3_prepare_v2(c->db,"SELECT score,solves FROM players WHERE user=?",-1,&s,0);sqlite3_bind_text(s,1,u,-1,SQLITE_TRANSIENT);int r=sqlite3_step(s);if(r==SQLITE_ROW){*score=sqlite3_column_int(s,0);*solves=sqlite3_column_int(s,1);}sqlite3_finalize(s);return r==SQLITE_ROW?0:1;}
int ctf_leaderboard(ctf_ctx*c,char*b,size_t n){sqlite3_stmt*s;sqlite3_prepare_v2(c->db,"SELECT user,score,solves FROM players ORDER BY score DESC,solves DESC,user LIMIT 10",-1,&s,0);size_t off=0;int rank=1;while(sqlite3_step(s)==SQLITE_ROW&&off<n){off+=(size_t)snprintf(b+off,n-off,"%d. %s — %d XP (%d solves)\n",rank++,(const char*)sqlite3_column_text(s,0),sqlite3_column_int(s,1),sqlite3_column_int(s,2));}sqlite3_finalize(s);return 0;}
